// 导出自定义书签数据 (版本 V1.1)
window.bookmarkData = {
  VERSION: 'V1.1',
  searchEngines: [
    {"name":"Bing","url":"https://cn.bing.com/search?q="},
    {"name":"Baidu","url":"https://www.baidu.com/s?wd="},
    {"name":"Yandex","url":"https://yandex.com/search?q="},
    {"name":"Google","url":"https://www.google.com/search?q="},
    {"name":"知乎","url":"https://www.zhihu.com/search?type=content&q="},
    {"name":"CSDN","url":"https://so.csdn.net/so/search?q="}
  ],
  categories: [
    {"id":"cat-empty","name":"未分类","icon":"📁"},
    {"id":"cat_1","name":"GH首页常用","icon":"🏠"},
    {"id":"cat_3","name":"学业官方","icon":"🎓"},
    {"id":"cat_4","name":"商城","icon":"🛒"},
    {"id":"cat_5","name":"翻译+论文","icon":"📝"},
    {"id":"cat_6","name":"开发学习","icon":"💻"},
    {"id":"cat_8","name":"在线工具","icon":"🛠️"},
    {"id":"all","name":"全部","icon":"📋"}
  ],
  bookmarks: [
    {"id":1,"name":"BiliBili","url":"https://www.bilibili.com/","description":"","category":"cat_1"},
    {"id":2,"name":"语雀","url":"https://www.yuque.com/dashboard/notes","description":"","category":"cat_1"},
    {"id":3,"name":"有道翻译","url":"https://dict.youdao.com/","description":"","category":"cat_1"},
    {"id":4,"name":"CSDN_内容中心","url":"https://mp.csdn.net/mp_blog/manage/article","description":"","category":"cat_1"},
    {"id":5,"name":"Deepseek","url":"https://chat.deepseek.com/","description":"","category":"cat_1"},
    {"id":6,"name":"元宝","url":"https://yuanbao.tencent.com/chat/naQivTmsDa","description":"","category":"cat_1"},
    {"id":7,"name":"千问QWEN","url":"https://www.qianwen.com/","description":"","category":"cat_1"},
    {"id":8,"name":"ChatGPT","url":"https://chatgpt.com/","description":"","category":"cat_8"},
    {"id":9,"name":"豆包","url":"https://www.doubao.com/chat/","description":"","category":"cat_1"},
    {"id":10,"name":"Kimi","url":"https://kimi.moonshot.cn/","description":"","category":"cat_1"},
    {"id":11,"name":"即梦AI-绘图","url":"https://jimeng.jianying.com/ai-tool/home","description":"","category":"cat_8"},
    {"id":12,"name":"上网登录","url":"https://xha.ouc.edu.cn/","description":"","category":"cat_3"},
    {"id":13,"name":"研究生信息门户","url":"https://my.ouc.edu.cn/#/home","description":"","category":"cat_3"},
    {"id":14,"name":"培养方案","url":"https://pgs.ouc.edu.cn/py/page/student/ckgrxxjh.htm","description":"","category":"cat_3"},
    {"id":15,"name":"海大正版软件","url":"http://ms.ouc.edu.cn/","description":"","category":"cat_3"},
    {"id":16,"name":"学信档案","url":"https://my.chsi.com.cn/archive/bab/index.action","description":"","category":"cat_3"},
    {"id":17,"name":"立创商城","url":"https://www.szlcsc.com/","description":"","category":"cat_4"},
    {"id":18,"name":"半导小芯","url":"http://www.semiee.com/","description":"","category":"cat_4"},
    {"id":19,"name":"淘宝","url":"https://www.taobao.com/","description":"","category":"cat_4"},
    {"id":20,"name":"京东","url":"https://www.jd.com/","description":"","category":"cat_4"},
    {"id":21,"name":"中国知网 - 检索","url":"https://www.cnki.net/","description":"","category":"cat_5"},
    {"id":22,"name":"谷歌学术","url":"https://scholar.google.com.hk/schhp?hl=zh-CN&as_sdt=0,5","description":"","category":"cat_5"},
    {"id":23,"name":"CNKI 学术翻译","url":"https://dict.cnki.net/index#","description":"","category":"cat_5"},
    {"id":24,"name":"DeepLy","url":"https://www.deepl.com/zh/translator","description":"","category":"cat_5"},
    {"id":25,"name":"百度翻译","url":"https://fanyi.baidu.com/","description":"","category":"cat_5"},
    {"id":26,"name":"沪江小 D - 日语","url":"https://dict.hjenglish.com/jp","description":"","category":"cat_5"},
    {"id":27,"name":"小绿鲸文献翻译","url":"https://www.xljsci.com/editor/","description":"","category":"cat_5"},
    {"id":28,"name":"立创开源平台","url":"https://wiki.lceda.cn/zh-hans/","description":"","category":"cat_6"},
    {"id":29,"name":"立创 EDA 专业版指南","url":"https://prodocs.lceda.cn/cn/quick-start.html","description":"","category":"cat_6"},
    {"id":30,"name":"中国大学 MOOC","url":"https://www.icourse163.org/","description":"","category":"cat_6"},
    {"id":31,"name":"Github","url":"https://github.com/GeorgeHuaR?tab=repositories","description":"","category":"cat_6"},
    {"id":32,"name":"菜鸟教程 (C#)","url":"https://www.runoob.com/csharp/csharp-tutorial.html","description":"","category":"cat_6"},
    {"id":33,"name":"GH_GithubPage","url":"https://georgehuar.github.io","description":"","category":"cat_6"},
    {"id":34,"name":"QQ邮箱","url":"https://wx.mail.qq.com/home/index?sid=zdgzZ4wZQVou9jNaAJRxaQAA#/list/1","description":"","category":"cat_8"},
    {"id":35,"name":"🍅番茄简谱","url":"http://zhipu.lezhi99.com/Zhipu-index.html","description":"","category":"cat_8"},
    {"id":36,"name":"在线钢琴","url":"https://www.autopiano.cn/","description":"","category":"cat_8"},
    {"id":37,"name":"中国曲谱网","url":"https://www.qupu123.com/Search","description":"","category":"cat_8"},
    {"id":38,"name":"简谱之家","url":"https://www.jianpu.net/jianpu/","description":"","category":"cat_8"},
    {"id":39,"name":"在线PDF编辑","url":"https://www.ilovepdf.com/zh-cn","description":"","category":"cat_8"},
    {"id":40,"name":"KS串口助手","url":"https://serial.baud-dance.com/#/","description":"","category":"cat_8"},
    {"id":42,"name":"图片工具（在线）","url":"https://docsmall.com/image-compress","description":"在线图片压缩、该尺寸等","category":"cat_8"}
  ]
};